name: lounchtime
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  url_launcher: ^6.1.3
  # data_table_2: ^2.3.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  # get: any
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

