// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRI3PjDSqZgTDLwDRpVTdFmuUQv4ODIo',
    appId: '1:652241926517:web:17fda6a96ed114f46bfb3c',
    messagingSenderId: '652241926517',
    projectId: 'launch-time',
    authDomain: 'launch-time.firebaseapp.com',
    storageBucket: 'launch-time.appspot.com',
    measurementId: 'G-5XW78YJB28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BjR9aYVuydrlfVt6A4z--aNuclTekqs',
    appId: '1:652241926517:android:b91e20b7672683cb6bfb3c',
    messagingSenderId: '652241926517',
    projectId: 'launch-time',
    storageBucket: 'launch-time.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSYMsNKvsOGy2rhxACh-Eyvrevqf3cOg',
    appId: '1:652241926517:ios:f83b141a576826326bfb3c',
    messagingSenderId: '652241926517',
    projectId: 'launch-time',
    storageBucket: 'launch-time.appspot.com',
    androidClientId: '652241926517-45c0mrs8ld7htn4foldp6ogdvmf956qn.apps.googleusercontent.com',
    iosClientId: '652241926517-vip5ba8egtsi8jup3oqtmbcir9q8g8s2.apps.googleusercontent.com',
    iosBundleId: 'com.ababildev.lounchtime.lounchtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSYMsNKvsOGy2rhxACh-Eyvrevqf3cOg',
    appId: '1:652241926517:ios:f83b141a576826326bfb3c',
    messagingSenderId: '652241926517',
    projectId: 'launch-time',
    storageBucket: 'launch-time.appspot.com',
    androidClientId: '652241926517-45c0mrs8ld7htn4foldp6ogdvmf956qn.apps.googleusercontent.com',
    iosClientId: '652241926517-vip5ba8egtsi8jup3oqtmbcir9q8g8s2.apps.googleusercontent.com',
    iosBundleId: 'com.ababildev.lounchtime.lounchtime',
  );
}
